"""add number to User

Revision ID: cfb0afcff4e3
Revises: 7191dd517a73
Create Date: 2025-06-07 15:21:32.770424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb0afcff4e3'
down_revision: Union[str, None] = '7191dd517a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('number', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'number')
    # ### end Alembic commands ###
