name: Test FastAPI CI/CD

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # --- Adicionado: Configuração do Python e execução dos testes ---
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio anyio # Ensure anyio is also installed if it's a plugin

    # --- Debugging Steps ---
    - name: Show current directory and list files
      run: |
        pwd
        ls -la
        ls -la test/
        ls -la test/mocks/
        ls -la test/services/

    - name: Print PYTHONPATH
      run: echo "PYTHONPATH is: $PYTHONPATH"
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: Print Python sys.path (how Python sees its paths)
      # This will show you exactly what Python considers its module search path
      run: |
        python -c "import sys; print(sys.path)"
      env:
        PYTHONPATH: ${{ github.workspace }}
    # --- End Debugging Steps ---

    - name: Run tests
      env:
        DATABASE_URL: sqlite+aiosqlite:///:memory:
        PYTHONPATH: ${{ github.workspace }} # Ensure it's set here too
      run: python -m pytest -W ignore::DeprecationWarning

    # ... (Seus passos de Docker buildx, login, build/push) ...
